<a href="https://colab.research.google.com/github/JamesGreen1210/PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


In [10]:
## Introduction to Tensors

### Creating tensors

# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [11]:
scalar.ndim

0

In [12]:
# Get tensor back as python int
scalar.item()

7

In [14]:
# Vector
vector = torch.tensor([7,7])
vector


tensor([7, 7])

In [15]:
vector.ndim

1

In [16]:
vector.shape

torch.Size([2])

In [18]:
# MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [19]:
MATRIX.ndim

2

In [20]:
MATRIX[0]

tensor([7, 8])

In [23]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [24]:
TENSOR.shape

torch.Size([1, 3, 3])

In [25]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### RANDOM TENSORS

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at the data -> update random numbers -> looks at the data -> update random numbers`

In [27]:
# Create a random tensors of size (3, 4)
random_tensor = torch.rand(10, 10)
random_tensor

tensor([[0.5421, 0.9642, 0.3977, 0.0195, 0.9344, 0.9833, 0.6244, 0.7269, 0.3492,
         0.1528],
        [0.8261, 0.7698, 0.7674, 0.7531, 0.4811, 0.8880, 0.7555, 0.7971, 0.9528,
         0.5360],
        [0.5377, 0.4579, 0.0753, 0.6465, 0.2544, 0.1227, 0.1789, 0.5606, 0.1141,
         0.4845],
        [0.0122, 0.4158, 0.9768, 0.5776, 0.5983, 0.4499, 0.5294, 0.1823, 0.2556,
         0.1521],
        [0.3300, 0.0078, 0.6357, 0.3574, 0.9613, 0.8319, 0.6627, 0.0281, 0.9290,
         0.3336],
        [0.7102, 0.8763, 0.4162, 0.1181, 0.5974, 0.5355, 0.6216, 0.5344, 0.1841,
         0.6032],
        [0.2709, 0.7105, 0.8117, 0.7976, 0.9731, 0.8310, 0.9323, 0.6104, 0.9616,
         0.1543],
        [0.5094, 0.8175, 0.4649, 0.6155, 0.3314, 0.9215, 0.4934, 0.1330, 0.1958,
         0.1966],
        [0.6740, 0.2393, 0.9069, 0.7575, 0.8286, 0.0185, 0.5362, 0.1436, 0.4018,
         0.9571],
        [0.9585, 0.2395, 0.8347, 0.2308, 0.9227, 0.9184, 0.2002, 0.7781, 0.5651,
         0.4796]])

In [30]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones


In [31]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [38]:
# Use torch.range()
one_to_ten = torch.arange(start=0, end=1000, step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [39]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

errors come from

1. Tensors not being the right data type
2. Tensors not being the right shape
3. Tensors not on the right device

In [40]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

### Tensor Attributes

1. `tensor.dtype`
2. `tensor.shape`
3. `tensor.device`

In [41]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2880, 0.7093, 0.4546, 0.2185],
        [0.2369, 0.3815, 0.4065, 0.2160],
        [0.4936, 0.5542, 0.9207, 0.7830]])

In [43]:
print(f"Datatype of tensor: {some_tensor.dtype}")
some_tensor.size()

Datatype of tensor: torch.float32


torch.Size([3, 4])

### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [44]:
# Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [46]:
# Mulitply tensor by 10
tensor * 10

tensor([100, 200, 300])

In [49]:
# Element wise multiplaction
print(tensor, "* ", tensor)
print(f"Equals: {tensor*tensor}")

tensor([10, 20, 30]) *  tensor([10, 20, 30])
Equals: tensor([100, 400, 900])


In [50]:
# Matrix Multiplication
torch.matmul(tensor,tensor)

tensor(1400)